name: schedule_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  

flutter:
  uses-material-design: true


